baseURL = 'https://kauefraga.github.io/blog/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
enableEmoji = true
title = 'Kauê Fraga Rodrigues'
theme = 'PaperMod'

[[menu.main]]
identifier = "sobre"
name = "Sobre"
url = "/about/"

[[menu.main]]
identifier = "projetos"
name = "Projetos"
url = "/projects/"
