baseURL = 'https://kauefraga.github.io/blog/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
enableEmoji = true
title = 'Blog do Kauê'
theme = 'PaperMod'

[[menu.main]]
name = 'Sobre'
url = '/sobre/'

[[menu.main]]
name = 'Projetos'
url = '/projetos/'

[[menu.main]]
name = 'Notas'
url = '/notas/'
