baseURL                = 'https://kauefraga.github.io/blog/'
languageCode           = 'pt-BR'
enableEmoji            = true
title                  = 'Kauê Fraga Rodrigues'
theme                  = 'PaperMod'
