baseURL = 'https://kauefraga.github.io/blog/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
enableEmoji = true
title = 'Blog do Kauê'
theme = 'PaperMod'


[params]
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowShareButtons = true
ShareButtons = ['linkedin', 'x', 'reddit']

[params.homeInfoParams]
Title = 'Oi!'
Content = '''
  Como você deve imaginar, me chamo Kauê. Tenho 16 anos e sou
  um entusiasta de tecnologia, mais especificamente, da programação.
  Gosto de criar ferramentas de desenvolvimento com usabilidade de outro mundo.
  Também adoro back end e tenho algum conhecimento em front end.
'''

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/kauefraga'

[[params.socialIcons]]
name = 'twitter'
url = 'https://twitter.com/rkauefraga'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/kauefraga/'

[[params.socialIcons]]
name = 'dev'
url = 'https://dev.to/kauefraga'

[[params.socialIcons]]
name = 'stackoverflow'
url = 'https://stackoverflow.com/users/25235442/kauefraga'

[[params.socialIcons]]
name = 'reddit'
url = 'https://www.reddit.com/user/kauefraga/'


[[menu.main]]
name = 'Sobre'
url = '/sobre/'

[[menu.main]]
name = 'Projetos'
url = '/projetos/'

[[menu.main]]
name = 'Notas'
url = '/notas/'
